# Generated by Django 3.0.1 on 2019-12-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.PositiveSmallIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'meses',
            },
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='rolPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'roles de persona',
            },
        ),
        migrations.CreateModel(
            name='tipoAporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'tipos de aporte',
            },
        ),
        migrations.CreateModel(
            name='tipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'tipos de evento',
            },
        ),
        migrations.CreateModel(
            name='relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('persona_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_de', to='endpoints.persona')),
                ('persona_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_propias', to='endpoints.persona')),
            ],
            options={
                'verbose_name_plural': 'relaciones',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='endpoints.rolPersona'),
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='endpoints.tipoEvento')),
            ],
            options={
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='aporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveSmallIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='endpoints.mes')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='endpoints.persona')),
                ('tipoAporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='endpoints.tipoAporte')),
            ],
            options={
                'verbose_name_plural': 'aportes',
            },
        ),
    ]
