# Generated by Django 3.0.1 on 2019-12-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoEstructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'tipos de estructura',
            },
        ),
        migrations.CreateModel(
            name='zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='estructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estructuras', to='endpoints.tipoEstructura')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estructuras', to='endpoints.zona')),
            ],
            options={
                'verbose_name_plural': 'estructuras',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='estructura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='endpoints.estructura'),
        ),
    ]
