# Generated by Django 3.0.1 on 2019-12-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_persona_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='endpoints.estructura'),
        ),
        migrations.AlterField(
            model_name='rolpersona',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
