# Generated by Django 3.0.1 on 2019-12-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_auto_20191227_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aporte',
            name='mes',
        ),
        migrations.AddField(
            model_name='aporte',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='mes',
        ),
    ]
