# Generated by Django 3.0.1 on 2019-12-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
