# Generated by Django 3.0.1 on 2019-12-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_auto_20191224_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='eventos',
            field=models.ManyToManyField(related_name='personas', to='endpoints.evento'),
        ),
    ]
