# Generated by Django 3.0.1 on 2019-12-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_auto_20191228_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
